version: '3'

services:
  backend:
    image: node:10
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/project
      - ./shared:/shared
    working_dir: /project
    tty: true
    stdin_open: true
    command: bash -c "yarn && yarn start:dev"
  movies:
    image: node:10
    volumes:
      - ./movies:/project
      - ./shared:/shared
    working_dir: /project
    tty: true
    stdin_open: true
    command: bash -c "yarn && yarn start:dev"
#    deploy:
#      replicas: 2
  queue:
    image: rabbitmq:3
    tty: true
    stdin_open: true
  database:
    image: postgres:11
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
